#!/bin/sh

CRONTAB=$1
shift
CROND_PARAMS=$@

ENTRYPOINT_USER=rclone
ENTRYPOINT_GROUP=rclone
ENTRYPOINT_HOME=/home
ENTRYPOINT_COMMAND="true"

entrypoint.sh \
  $ENTRYPOINT_USER \
  $ENTRYPOINT_GROUP \
  $ENTRYPOINT_HOME \
  $ENTRYPOINT_COMMAND

crontab -u $ENTRYPOINT_USER $CRONTAB

crond $CROND_PARAMS
