#!/bin/sh

CRONTAB_DIR=$1
shift
CROND_PARAMS=$@

ENTRYPOINT_USER=rclone
ENTRYPOINT_GROUP=rclone
ENTRYPOINT_HOME=/home
ENTRYPOINT_COMMAND=crontab -u $ENTRYPOINT_USER -c $CRONTAB_DIR

entrypoint.sh \
  $ENTRYPOINT_USER \
  $ENTRYPOINT_GROUP \
  $ENTRYPOINT_HOME \
  $ENTRYPOINT_COMMAND

crond $CROND_PARAMS
